
name: nodejs_test
version: 0.0.1
language: nodejs
description: Run test use `npm test`
public: true
tags:
  - nodejs
  - test
inputs:
  - name: FLOW_ENABLE_FAILURE
    editable: true
    options:
      - TRUE
      - FALSE
outputs:
script_path: ./run.sh  
  
template: |  
  
  